---
- name: Create directory for RHEL scripts and tools
  ansible.builtin.file:
    path: /opt/rhel/bin
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy RHEL scripts and tools
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/rhel/bin
    owner: root
    group: root
    mode: 0755
  with_fileglob:
    - scripts/*.sh
