---
- name: Remove MAC address from network configuration
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    state: absent
    regexp: '^HWADDR'
  when:
    - ansible_facts['system_vendor'] == "Microsoft Corporation"
    - ansible_facts['product_name'] == "Virtual Machine"
