---
# Install Azure server management tools
- name: Installation of Azure packages for RHEL
  ansible.builtin.dnf:
    name:
      - blobfuse
      - cloud-utils-growpart
      - gdisk
      - hyperv-daemons
      - WALinuxAgent
    state: present
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version']|int >= 8

- name: Remove RHEL packages not needed on Azure
  ansible.builtin.dnf:
    name:
      - rhui-azure-rhel8
    state: absent
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version']|int == 8
