---
# Add hardware related tools
- name: Installation of base packages for RHEL and clones for major release 8 and above
  ansible.builtin.dnf:
    name:
      - dmidecode
      - lm_sensors
      - pciutils
    state: present
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version']|int >= 8
