---
# Add physical host related tools
- name: Installation of physical host tools
  ansible.builtin.dnf:
    name:
      - dmidecode
      - lm_sensors
      - pciutils
    state: present
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version']|int >= 8
